# -*- coding: utf-8 -*-
"""GeoDesastres Brasil: Análise e Visualização Interativa de Desastres Naturais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfwZTizRQ5gly3sZvw-6Oh-5uzE_x7zY
"""

!pip install geopandas folium matplotlib owslib plotly pandas

import folium
import matplotlib.pyplot as plt
import plotly.express as px
import pandas as pd

def adicionar_camada_wms(mapa, wms_url, layer_name, nome_exibicao):
    folium.raster_layers.WmsTileLayer(
        url=wms_url,
        layers=layer_name,
        name=nome_exibicao,
        fmt='image/png',
        transparent=True,
        attr='GeoPortal SGB'
    ).add_to(mapa)

m = folium.Map(location=[-14.2350, -51.9253], zoom_start=4)

wms_urls = {
    'Corrida de Massa': "http://geoportal.sgb.gov.br/server/services/gestaoterritorial/corrida_de_massa/MapServer/WMSServer?service=WMS",
    'Enxurrada': "http://geoportal.sgb.gov.br/server/services/gestaoterritorial/enxurrada/MapServer/WMSServer?service=WMS",
    'Perigo': "http://geoportal.sgb.gov.br/server/services/gestaoterritorial/perigo/MapServer/WMSServer?service=WMS",
    'Risco Geológico': "http://geoportal.sgb.gov.br/server/services/gestaoterritorial/risco/MapServer/WMSServer?service=WMS"
}

adicionar_camada_wms(m, wms_urls['Corrida de Massa'], '0', 'Corrida de Massa')
adicionar_camada_wms(m, wms_urls['Enxurrada'], '0', 'Enxurrada')
adicionar_camada_wms(m, wms_urls['Perigo'], '0', 'Perigo')
adicionar_camada_wms(m, wms_urls['Risco Geológico'], '0', 'Risco Geológico')

folium.LayerControl().add_to(m)

m

dados = pd.DataFrame({
    'Ano': [2018, 2019, 2020, 2021, 2022, 2023],
    'Corrida de Massa': [15, 20, 25, 22, 30, 35],
    'Enxurrada': [10, 12, 18, 20, 25, 28],
    'Perigo': [5, 8, 10, 12, 14, 15]
})

fig = px.line(dados, x='Ano', y=['Corrida de Massa', 'Enxurrada', 'Perigo'],
              title='Ocorrências de Desastres Naturais por Ano',
              labels={'value':'Número de Ocorrências', 'variable':'Tipo de Desastre'})
fig.show()

dados.to_csv('desastres_naturais_brasil.csv', index=False)

print("Mapas WMS carregados com sucesso! Visualize os desastres naturais diretamente no mapa interativo.")
print("Gráficos interativos e dados exportados com sucesso!")